import FontAwesome from "@expo/vector-icons/FontAwesome"

export const REGISTERED_FONTS = {
  SpaceMono: require("@/assets/fonts/SpaceMono-Regular.ttf"),
  "Montserrat-ExtraLight": require("@/assets/fonts/Montserrat/Montserrat-ExtraLight.ttf"),
  "Montserrat-ExtraLightItalic": require("@/assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf"),
  "Montserrat-Light": require("@/assets/fonts/Montserrat/Montserrat-Light.ttf"),
  "Montserrat-LightItalic": require("@/assets/fonts/Montserrat/Montserrat-LightItalic.ttf"),
  "Montserrat-Thin": require("@/assets/fonts/Montserrat/Montserrat-Thin.ttf"),
  "Montserrat-ThinItalic": require("@/assets/fonts/Montserrat/Montserrat-ThinItalic.ttf"),
  Montserrat: require("@/assets/fonts/Montserrat/Montserrat-Regular.ttf"),
  "Montserrat-Italic": require("@/assets/fonts/Montserrat/Montserrat-Italic.ttf"),
  "Montserrat-Medium": require("@/assets/fonts/Montserrat/Montserrat-Medium.ttf"),
  "Montserrat-MediumItalic": require("@/assets/fonts/Montserrat/Montserrat-MediumItalic.ttf"),
  "Montserrat-SemiBold": require("@/assets/fonts/Montserrat/Montserrat-SemiBold.ttf"),
  "Montserrat-SemiBoldItalic": require("@/assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf"),
  "Montserrat-Bold": require("@/assets/fonts/Montserrat/Montserrat-Bold.ttf"),
  "Montserrat-BoldItalic": require("@/assets/fonts/Montserrat/Montserrat-BoldItalic.ttf"),
  "Montserrat-ExtraBold": require("@/assets/fonts/Montserrat/Montserrat-ExtraBold.ttf"),
  "Montserrat-ExtraBoldItalic": require("@/assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf"),
  "Montserrat-Black": require("@/assets/fonts/Montserrat/Montserrat-Black.ttf"),
  "Montserrat-BlackItalic": require("@/assets/fonts/Montserrat/Montserrat-BlackItalic.ttf"),
  "Roboto-Thin": require("@/assets/fonts/Roboto/Roboto-Thin.ttf"),
  "Roboto-ThinItalic": require("@/assets/fonts/Roboto/Roboto-ThinItalic.ttf"),
  "Roboto-Light": require("@/assets/fonts/Roboto/Roboto-Light.ttf"),
  "Roboto-LightItalic": require("@/assets/fonts/Roboto/Roboto-LightItalic.ttf"),
  Roboto: require("@/assets/fonts/Roboto/Roboto-Regular.ttf"),
  "Roboto-Italic": require("@/assets/fonts/Roboto/Roboto-Italic.ttf"),
  "Roboto-Medium": require("@/assets/fonts/Roboto/Roboto-Medium.ttf"),
  "Roboto-MediumItalic": require("@/assets/fonts/Roboto/Roboto-MediumItalic.ttf"),
  "Roboto-Bold": require("@/assets/fonts/Roboto/Roboto-Bold.ttf"),
  "Roboto-BoldItalic": require("@/assets/fonts/Roboto/Roboto-BoldItalic.ttf"),
  "Roboto-Black": require("@/assets/fonts/Roboto/Roboto-Black.ttf"),
  "Roboto-BlackItalic": require("@/assets/fonts/Roboto/Roboto-BlackItalic.ttf"),
  ...FontAwesome.font,
}
